### ISSUE TITLE
map over values within signals

### ISSUE THREAD

**Issue by obcan** [bodil/purescript-signal#37]
Great work! 
Is possible map over produced values within signal like in RxJS functors?
I mean something like this:
```purescript
import Prelude hiding (div)
import Signal
import Signal.DOM

doubleCoordinates c = c {x = c.x * 2, y = c.y * 2}

-- | produce new signal with doubled coordinates from origin
main = mousePos ~> doubleCoordinates
```

**Comment by michaelficarra** [comment]
Yes, exactly what you've written should work. What's wrong?

**Comment by obcan** [comment]
This pseudocode produce type mismatch Error. Function passed to functor ~> must be type of Signal CoordinatePair -> Signal CoordinatePair but doubleCoordinates have type CoordinatePair on the right side. Maybe I missed something and only one way is use to Foldp.

**Comment by kRITZCREEK** [comment]
Your code fails because of the type of mousePos:

```purescript
mousePos :: forall e. Eff (dom :: DOM | e) (Signal CoordinatePair)
```

As you can see the Signal is "wrapped" inside an `Eff` which also has a functor instance. The `~>` or map now tries to apply `doubleCoordinates` to a `Signal CoordinatePair` instead of a Coordinate pair.
We can solve this by first extracting the mouse Signal from mousePosition and then mapping.

```purescript
import Prelude hiding (div)
import Signal
import Signal.DOM

doubleCoordinates c = c {x = c.x * 2, y = c.y * 2}

-- | produce new signal with doubled coordinates from origin
main = do
  mouse <- mousePos
  pure (mouse ~> doubleCoordinates)
```
